sudo: false
language: erlang
install: true
before_script:
- wget https://s3.amazonaws.com/rebar3/rebar3
- chmod +x rebar3
env: PATH=$PATH:.
script: make travis
cache:
  directories:
  - $HOME/.cache/rebar3/
otp_release:
- 18.0
- 18.1
- 18.2
- 18.2.1
- 18.3
- 19.0
- 19.1
- 19.2
- 19.3
- 20.0
- 20.1
- 20.2
