name: Common Test

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test on OTP ${{ matrix.tuple.otp_version }} and ${{ matrix.tuple.os }}
    runs-on: ${{ matrix.tuple.os }}

    strategy:
      fail-fast: false
      matrix:
        tuple:
          - otp_version: 25
            os: ubuntu-22.04
            rebar3_version: 3.22
          - otp_version: 24
            os: ubuntu-22.04
            rebar3_version: 3.22
          - otp_version: 23
            os: ubuntu-20.04
            rebar3_version: 3.15
          - otp_version: 22
            os: ubuntu-20.04
            rebar3_version: 3.15

    steps:
    - uses: actions/checkout@v4

    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.tuple.otp_version }}
        rebar3-version: ${{ matrix.tuple.rebar3_version }}

    - name: Compile
      run: rebar3 compile
    - name: EUnit tests
      run: rebar3 eunit
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: XRef
      run: rebar3 xref

    - name: Covertool
      run: rebar3 covertool generate
    - uses: codecov/codecov-action@v4
      with:
        files: _build/test/covertool/elli.covertool.xml
        env_vars: OTP_VERSION
